COMP    = hipcc 
FLAGS   = -fopenmp --target=x86_64-pc-linux-gnu -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx90a

vecadd: vecadd.o
	${COMP} ${FLAGS} vecadd.o -o vecadd

vecadd.o: vecadd.cpp
	${COMP} ${FLAGS} -c vecadd.cpp

.PHONY: clean

clean:
	rm -f vecadd *.o
