COMP    = hipcc 
FLAGS   = -v -fopenmp -target x86_64-pc-linux-gnu -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx90a
MPIFLAGS = -I${MPICH_DIR}/include -L${MPICH_DIR}/lib -lmpi ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}

jacobi: jacobi.c
	${COMP} ${FLAGS} ${MPIFLAGS} jacobi.c -o jacobi

.PHONY: clean

clean:
	rm -f jacobi *.o
