COMP  = hipcc
FLAGS = --amdgpu-target=gfx90a

INCLUDES  = -I${MPICH_DIR}/include
LIBRARIES =  -L${MPICH_DIR}/lib -lmpi ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}

vAdd_hip: vAdd_hip.o
	${COMP} ${FLAGS} ${LIBRARIES} vAdd_hip.o -o vAdd_hip

vAdd_hip.o: vAdd_hip.hip
	${COMP} ${FLAGS} ${INCLUDES} -c vAdd_hip.hip

.PHONY: clean

clean:
	rm -f vAdd_hip *.o
